### ISSUE TITLE
Handle multiple ParaVision versions

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/COSplay#21]
On the AIC 9T computer there are multiple ParaVision versions, this seems to be a challenge for COSplay:

```
[mri@biospec94 opt]$ COSplay 
Traceback (most recent call last):
  File "/usr/local/bin/COSplay", line 11, in <module>
    load_entry_point('COSplay==0.0.0', 'console_scripts', 'COSplay')()
  File "/usr/local/lib/python3.6/site-packages/COSplay-0.0.0-py3.6.egg/cosplay/cli.py", line 64, in main
  File "/usr/local/lib/python3.6/site-packages/COSplay-0.0.0-py3.6.egg/cosplay/server.py", line 320, in main
  File "/usr/local/lib/python3.6/site-packages/COSplay-0.0.0-py3.6.egg/cosplay/server.py", line 47, in find_current_scan_dir
RuntimeError: Multiple versions of ParaVision found. List of folders found: ['/opt/PV6.Beta.0.41/data/mri/', '/opt/PV5.1/data/mri/', '/opt/PV6.Beta.0.42/data/mri/', '/opt/PV6.Beta.0.31/data/mri/', '/opt/PV6.0/data/mri/', '/opt/PV6.0.1/data/mri/', '/opt/PV6.Beta.0.46/data/mri/', '/opt/PV6.Beta.0.35/data/mri/']
```

As it happens the used version is `'/opt/PV6.0/data/mri/'` - so not the newest. Ideally COSplay would just look for the most recent scan directory, regarless of which PV version is used or how many there are present.

**Comment by TheChymera** [comment]
This is now manually solvable after https://github.com/IBT-FMI/COSplay/commit/f82df6ca583027188935afabb8f6853818138304 .

If multiple directories are present, the user is prompted to select one via the relevant command line argument. It would be even better, though, if this was automatically handled.
